version: "2"
services:
    jenkins_with_docker:
      image: jenkins_with_docker_compose:latest
      container_name: "jenkins_with_docker_compose"
      ports:
       - 8080:8080
       - 50000:50000
      networks:
       - ci_nw
      volumes:
       - /var/jenkins_home:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock
       - /usr/bin/docker:/usr/bin/docker
    db:
     image: postgres:latest
     container_name: "postgresql_db"
     networks:
      - ci_nw
     environment:
        POSTGRES_USER: sonar
        POSTGRES_PASSWORD: sonarpasswd
     volumes:
      - /var/postgres-data:/var/lib/postgresql/data
    sonarqube:
      image: sonarqube:lts
      ports:
        - "9000:9000"
        - "9002:9002"
      networks:
        - ci_nw
      environment:
        SONARQUBE_JDBC_USERNAME: sonar
        SONARQUBE_JDBC_PASSWORD: sonarpasswd
        SONARQUBE_JDBC_URL: "jdbc:postgresql://db:5432/sonar"
      depends_on:
        - db
networks:
  ci_nw: